org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric properties for Minecraft 1.21.11 (see https://fabricmc.net/develop)
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
loom_version=1.18.2

# Mod properties
version=1.0.0
group=dev.donuthud

# Dependencies
fabric_api_version=0.141.6+1.21.11
